name: Deploy
on:
  workflow_dispatch:
#   push:
#     branches:
#       - main
jobs:
  build:
    name: Deploy all
    runs-on: self-hosted
    steps:
      - name: Deploy all
        run: |
          echo "Hello world!!!"
          sleep 10s
